name: Unit tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install Python dependencies
        run: python -m pip install coverage requests
      - name: Run tests with coverage
        working-directory: ./tests
        run: coverage run --branch -m unittest discover
